"""empty message

Revision ID: 91c1ce42c4bc
Revises: 4d63257043e4
Create Date: 2020-02-24 22:54:46.910393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c1ce42c4bc'
down_revision = '4d63257043e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societydetail',
    sa.Column('societyname', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('society_type', sa.String(length=64), nullable=True),
    sa.Column('fencing', sa.String(length=64), nullable=True),
    sa.Column('guard', sa.String(length=64), nullable=True),
    sa.Column('no_of_wings', sa.Integer(), nullable=True),
    sa.Column('no_of_floors', sa.Integer(), nullable=True),
    sa.Column('no_of_flats', sa.Integer(), nullable=True),
    sa.Column('total_flats', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_no', sa.String(length=10), nullable=True),
    sa.Column('email_id', sa.String(length=64), nullable=True),
    sa.Column('service_lift', sa.String(length=64), nullable=True),
    sa.Column('lift_capacity', sa.Integer(), nullable=True),
    sa.Column('vechile_parking', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('societyname'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('society_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('societydetail')
    # ### end Alembic commands ###
